<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Fisco</RootNamespace>
    <AssemblyName>Fisco</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <!-- NuGet Packaging Properties -->
    <PackageId>FiscoCore</PackageId>
    <Version>2.0.0</Version>
    <Authors>Manoel Victor Silva Lira</Authors>
    <Company>Manoel Victor Silva Lira</Company>
    <Product>Fisco</Product>
    <Title>Fisco.dll - Biblioteca para Impressoras Térmicas</Title>
    <Description>Biblioteca de alto desempenho para geração, renderização e impressão de documentos e cupons fiscais em impressoras térmicas (58mm e 80mm) para .NET Core 8.0 até 10 usando SkiaSharp.</Description>
    <PackageTags>thermal-printer;receipt;cupom-fiscal;printer;skiasharp;fisco;escpos</PackageTags>
    <PackageProjectUrl>https://github.com/manoel0810/Fisco</PackageProjectUrl>
    <RepositoryUrl>https://github.com/manoel0810/Fisco</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>

  <Import Project="..\Fisco.Shared\Fisco.Shared.projitems" Label="Shared" />

</Project>
